# Generated by Django 3.0.4 on 2020-10-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(max_length=90),
        ),
    ]
