# Generated by Django 3.0.4 on 2020-10-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201019_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default='', max_length=90),
        ),
    ]
