# Generated by Django 3.0.4 on 2020-07-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
    ]
